version: '3'
services:
  app:
    build: .
    command: bundle exec puma -C config/puma.rb -e production
    volumes:
      - .:/MolkkyRecord
      - public-data:/MolkkyRecord/public
      - tmp-data:/MolkkyRecord/tmp
      - log-data:/MolkkyRecord/log
    environment:
      - DB_CONNECTION=mysql
      - DB_PORT=3306
      - DB_HOST=<%= ENV.fetch("DB_HOST) %>
      - DB_DATABASE=<%= ENV.fetch("DB_DATABASE") %>
      - DB_USERNAME=<%= ENV.fetch("DB_USERNAME") %>
      - DB_PASSWORD=<%= ENV.fetch("DB_PASSWORD") %>
    stdin_open: true
    tty: true
    networks:
      - MolkkyRecord-network
  web:
    build:
      context: ./nginx_docker
    volumes:
      - public-data:/MolkkyRecord/public
      - tmp-data:/MolkkyRecord/tmp
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - MolkkyRecord-network
volumes:
  public-data:
  tmp-data:
  log-data:
  mysql-data:
networks:
  MolkkyRecord-network:
    external: true
