version: '3'
services:
  # =========ローカルと本番切り替え===========
  # db:
  #   image: mysql:5.7
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #   ports:
  #     - '3306:3306'
  #   command: --default-authentication-plugin=mysql_native_password
  #   volumes:
  #     - mysql-data:/var/lib/mysql
  #   networks:
  #     - MolkkyRecord-network
  # ======================================
  app:
    build: .
    # =========ローカルと本番切り替え===========
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    # ======================================
    command: bundle exec puma -C config/puma.rb -e production
    volumes:
      - .:/MolkkyRecord
      - public-data:/MolkkyRecord/public
      - tmp-data:/MolkkyRecord/tmp
      - log-data:/MolkkyRecord/log
    ports:
      - "3000:3000"
    # =========ローカルと本番切り替え===========
    # depends_on:
    #   - db
    # ======================================
    stdin_open: true
    tty: true
    command: bundle exec rails server -b 0.0.0.0
    networks:
      - MolkkyRecord-network
  web:
    build:
      context: ./nginx_docker
    volumes:
      - public-data:/MolkkyRecord/public
      - tmp-data:/MolkkyRecord/tmp
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - MolkkyRecord-network
  volumes:
    public-data:
    tmp-data:
    log-data:
    mysql-data:
  networks:
    MolkkyRecord-network:
      external: true
