version: '3'
services:
  db:
    image: mysql:5.7.34
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - MolkkyRecord-network
  app:
    build: .
    command: bundle exec puma -C config/puma.rb -e production
    volumes:
      - .:/MolkkyRecord
      - public-data:/MolkkyRecord/public
      - tmp-data:/MolkkyRecord/tmp
      - log-data:/MolkkyRecord/log
    stdin_open: true
    tty: true
    networks:
      - MolkkyRecord-network
  web:
    build:
      context: ./nginx_docker
    volumes:
      - public-data:/MolkkyRecord/public
      - tmp-data:/MolkkyRecord/tmp
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - MolkkyRecord-network
volumes:
  public-data:
  tmp-data:
  log-data:
  mysql-data:
networks:
  MolkkyRecord-network:
    external: true
