version: 2.1
jobs:
  build:
    docker:
    - image: circleci/ruby:2.6.7-node-browsers
    working_directory: ~/MolkkyRecord

    steps:
    - checkout
    - run:
        name: Install Docker Compose
        command: |
          curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64 > ~/docker-compose
          chmod +x ~/docker-compose
          sudo mv ~/docker-compose /usr/local/bin/docker-compose
    - run: env > ~/.env
    - run:
        name: docker-compose up --build -d
        command: |
          set -x
          docker-compose up --build -d
    - run:
        name: rubocop
        command: |
          set -x
          docker-compose exec app bundle exec rubocop --require rubocop-airbnb
    - run:
        name: docker-compose exec app rails db:create
        command: |
          set -x
          docker-compose exec app rails db:create RAILS_ENV=test
    - run:
        name: docker-compose exec app rails db:migrate 
        command: |
          set -x
          docker-compose exec app rails db:migrate RAILS_ENV=test
    - run:
        name: docker-compose down
        command: |
          set -x
          docker-compose down
    - run:
        name: docker-compose up -d
        command: |
          set -x
          docker-compose up -d
    - run:
        name: docker-compose exec app rspec
        command: |
          set -x
          docker-compose exec app rspec
    - run:
        name: docker-compose down
        command: docker-compose down

    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "Gemfile.lock" }}
        - v1-dependencies-

    - run:
        name: install dependencies
        command: |
          gem install bundler -v 2.0.2
          bundle install --jobs=4 --retry=3 --path vendor/bundle

    - save_cache:
        paths:
        - ./vendor/bundle
        key: v1-dependencies-{{ checksum "Gemfile.lock" }}

    # Database setup
    - run: mv ./config/database.yml.ci ./config/database.yml

    # Database setup
    - run:
        name: Databasesetup
        command: |
          bundle exec rake db:create
          bundle exec rake db:schema:load

    # collect reports
    - store_test_results:
        path: /tmp/test-results
    - store_artifacts:
        path: /tmp/test-results
        destination: test-results
