version: 2.1
jobs:
  rspec:
    working_directory: ~/Molkkyrecord
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup environment variable
          command: |
            echo "export COMPOSE_FILE=docker-compose.yml" >> $BASH_ENV
      - run:
          name: Containers build
          command: |
            set -x
            docker-compose build
      - run:
          name: Create network
          command: |
            docker network create MolkkyRecord-network
      - run:
          name: Start containers
          command: |
            set -x
            docker-compose up -d
      - run:
          name: Down containers
          command: |
            set -x
            docker-compose down
      - run:
          name: Create db
          command: |
            set -x
            docker-compose run app rails db:create db:migrate
      - run:
          name: Run rspec
          command: docker-compose run app rspec

  rubocop:
    working_directory: ~/Molkkyrecord
    docker:
      - image: circleci/ruby:2.6.7
    steps:
      - checkout
      - restore_cache:
          keys:
            - gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gemfiles-{{ .Branch }}-
            - gemfiles-master-
      - run: bundle config --local path vendor/bundle
      - run:
          name: bundle install
          command: bundle check || bundle install --jobs=8 --clean
      - run:
          name: Run rubocop
          command: bundle exec rubocop --parallel
      - save_cache:
          key: gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

  deploy:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:  
            - "b9:f2:b7:5a:ac:66:cc:08:2d:ec:43:0a:46:a7:a3:43"
      - run: ssh -p $PORT $USER_NAME@$HOST_NAME "cd /MolkkyRecord && git pull origin add-circleci"
      - run: docker-compose build
      - run: docker-compose run app rails assets:precompile RAILS_ENV=production
      - run: docker-compose up -d

orbs:
  build-tools: circleci/build-tools@2.6.3
  jq: circleci/jq@1.9.1
workflows:
  version: 2.1
  build:
    jobs:
      - rspec
      - rubocop
      - deploy:
          requires:
            - rspec
            - rubocop
          filters:
            branches:
              only: add-circleci
