version: 2.1
jobs:
  test:
    machine:
      image: circleci/classic:edge
    working_directory: ~/MolkkyRecord
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64 > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run: env > ~/.env
      - run:
          name: docker-compose up --build -d
          command: |
            set -x
            docker-compose up --build -d
      - run:
          name: rubocop
          command: |
            set -x
            docker-compose exec app bundle exec rubocop --require rubocop-airbnb
      - run:
          name: docker-compose exec app rails db:create
          command: |
            set -x
            docker-compose exec app rails db:create
      - run:
          name: docker-compose exec app rails db:migrate 
          command: |
            set -x
            docker-compose exec app rails db:migrate
      - run:
          name: docker-compose down
          command: |
            set -x
            docker-compose down
      - run:
          name: docker-compose up -d
          command: |
            set -x
            docker-compose up -d
      - run:
          name: docker-compose exec app rspec
          command: |
            set -x
            docker-compose exec app bin/bundle exec rspec
      - run:
          name: docker-compose down
          command: docker-compose down
